### PR TITLE
Add various code refactorings

### PR DESCRIPTION
**Pull request by tranzystorek-io**
I split the changes into separate commits to make review easier, initial highlights:

- Avoid redundant 'as u16' casts
- Use is_empty instead of len checks
- Use Option::map if applicable
- Use Option::as_deref to simplify some matches
- Simplify match_or_insert
- Use Deref to avoid clones and simplify expressions
- Provide correct octal literal as file permissions
- Use struct-init-with-default syntax
- Avoid cloning where unnecessary
- Use arrays as iterators
- Use if let instead of match in parse_hosts
- Simplify start subcommand procedure

### CODE REVIEW

**Comment by erikh** [comment]
it's gonna take a week or so to likely get through the changes here. Just wanted to set the expectation.

**Comment by erikh** [comment]
After a lot of thought, I'm really sorry to do this to you but...

these changes are a lot of ... stuff. And I'm really happy you did this! I just don't think I'll feel comfortable hitting the merge button on the whole set. Additionally, over the next few weeks zeronsd is going to change hopefully rapidly and in large complex ways.

So instead of throwing your patches away (not something I want to do) in lieu of not being able to merge them later, I would like to suggest this:

Submit one PR for each commit, or at least, independent changes. This way, if something conflicts as we're working on the new stuff(tm) we can address it quickly; either you rebase or we merge/reject and so on, without tramping the rest of your hard work.

Does that sound reasonable to you? I won't close this just yet, but I would ideally like this resolved by early next week if that's amenable to you. We should be making our big changes starting late next week.

**Comment by tranzystorek-io** [comment]
Sounds OK! I'm really glad you've taken the time to get through these changes and I absolutely don't want to interfere with this project's design etc.

I won't have any problem splitting those changes in my local repo so this PR can be closed.

**Comment by erikh** [comment]
Wonderful! Thanks for being so understanding. Closing this, looking forward to the PRs!

**Pull request closed without merging**
